server:
  port: 80

#Eureka
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息，默认为true。单点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#启动hystrix
feign:
  hystrix:
    enabled: true



ribbon:
  #建立连接后从服务器读取到可用资源信息的时间
  ReadTimeout: 5000
  #指的是建立可靠连接所用的时间
  ConnectTime: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000


